### ISSUE TITLE
Package Structure

### ISSUE THREAD

**Issue by nigel-gott** [asqui/psycopg-nestedtransactions#5]
So we have two packages right now, nestedtransactions and pyscopg-nestedtransactions. What package structure do we actually want? Using a - in a package name in python is horrible so perhaps instead it should be a nested package like:

pyscopg.nestedtransactions 

Also if the end goal is getting the code into pyscopg2 itself then I guess the package should be: 

pyscopg2.nestedtransactions

**Comment by asqui** [comment]
I removed the empty `psycopg-nestedtransactions` package in 02bdf9b9, leaving just the `nestedtransaction` package.

So at the moment use would be:-

    $ pip install psycopg-nestedtransactions

    from nestedtransactions.transaction import Transaction
    with Transaction(...):
        ...

Ultimately I'm hoping that we can contribute this to psycopg2.extras, so then use would be:

    $ # No manual installation required; included with psycopg2 package

    from psycopg2.extras import Transaction
    with Transaction(...):
        ...

I'll close this issue for now, but please comment if you have any further feedback.
