### ISSUE TITLE
Don't rollback existing user transactions

### ISSUE THREAD

**Issue by nigel-gott** [asqui/psycopg-nestedtransactions#7]
Currently if a user does this:
```python
cxn.autocommit = False
cur.execute('INSERT INTO table VALUES ('A'))
with Transaction(cxn):
    cur.execute('INSERT INTO table VALUES ('B'))
    raise Exception("uh oh")
```

Both inserts will be rolled back because the transaction begins on the first insert and our context manager doesn't start another one at the beginning. 

The obvious fix is just commit when we enter into our managed transaction for the very first time from 'user' code (and not when entering into a nested transaction). However i can see this initial commit not being that expected for the user / a hidden gotcha?

We could just throw if someone starts one of our transactions with autocommit off already, but that feels even more horrible.

**Comment by nigel-gott** [comment]
Or wait, if there is already an open transaction when we enter our top level transaction we can just use a save point just like if we were in a nested one.

**Comment by asqui** [comment]
I was initially thinking of enforcing that no transaction is in progress
when entering the context manager, but I like your idea of detecting the
situation and coping appropriately.

+1

This would allow for better interoperation where you are introducing this
context manager in the middle of existing code that already uses a
transaction.

**Comment by asqui** [comment]
This is now supported, and covered by the following test case: `test_autocommit_off_transaction_in_progress_successful_exit_leaves_transaction_running`
https://github.com/asqui/psycopg-nestedtransactions/blob/master/tests/test_transaction.py#L98
